### ISSUE TITLE
use jq -r instead of piping to tr

### ISSUE THREAD

**Issue by jorhett** [selivan/ansible-ssh#8]
Just FYI you can greatly simplify this code by using jq features better ;-) Raw mode will drop the quotes, and you can specify an alternative value for a null result. Seems like you want no value, so ...

```
ansible_ssh_host=$(echo "$inventory" | jq -r '.ansible_ssh_host? // empty')
```

Using single quotes around the .jq query will prevent metacharacters from being interpreted by the shell

**Comment by selivan** [comment]
Thanks!

Done all that: 6aaf589 6e35e95 35ed5d8
